import { EmailService } from "@/services/email.service";
import {
  getDueDigests,
  getPreferencesForCampaign,
  markNotified,
} from "@/services/notification-preferences.service";
import { isMilestoneEvent, type ProgressEvent } from "@/lib/notification-schedule";
import {
  milestoneEmailHtml,
  type MilestoneEmailImpactMetrics,
} from "@/services/campaign.service";

export const runtime = "nodejs";

const emailService = new EmailService();

// ── Rendering ─────────────────────────────────────────────────────────────────

export interface DigestContent {
  subject: string;
  html: string;
}

export function renderDigestEmail(
  campaignId: string,
  campaignName: string,
  progressPct: number,
  trees: number,
): DigestContent {
  return {
    subject: `${campaignName}: ${progressPct}% funded`,
    html: `<div style="font-family:sans-serif">
  <h2>${campaignName} progress</h2>
  <p>The campaign you sponsor is now <strong>${progressPct}% funded</strong> with <strong>${trees}</strong> trees planted.</p>
  <p><a href="https://fundable.stellar/campaigns/${campaignId}">View campaign</a></p>
</div>`,
  };
}

/**
 * Render a rich milestone email for a **sponsor** (backer-facing copy).
 *
 * When `metrics` are provided the email body includes the full four-column
 * impact card (trees planted / verified, CO₂ offset, sponsor count,
 * raised/goal) generated by `milestoneEmailHtml`. (#915)
 */
export function renderMilestoneEmail(
  campaignId: string,
  campaignName: string,
  milestoneKey: string,
  metrics?: MilestoneEmailImpactMetrics,
): DigestContent {
  const milestoneLabels: Record<string, string> = {
    "25_percent": "25% funded 🌱",
    "50_percent": "Halfway there — 50% funded 🌳",
    "75_percent": "75% funded 🌿",
    goal_reached: "Goal reached! 🎉",
  };
  const milestonePercentages: Record<string, number> = {
    "25_percent": 25,
    "50_percent": 50,
    "75_percent": 75,
    goal_reached: 100,
  };

  const label = milestoneLabels[milestoneKey] ?? `Milestone reached: ${milestoneKey}`;
  const percentage = milestonePercentages[milestoneKey] ?? 0;

  // Use the shared campaign template (audience="sponsor") when we have metrics,
  // so both creator and sponsor emails have the same impact table quality.
  const html = metrics
    ? milestoneEmailHtml(campaignName, percentage, metrics, "sponsor")
    : `<div style="font-family:sans-serif;max-width:600px;margin:0 auto;">
  <h2 style="color:#4f2d99;">${campaignName}</h2>
  <p style="font-size:16px;">${label}</p>
  <p>The campaign you back just hit a milestone.</p>
  <p><a href="https://fundable.stellar/campaigns/${campaignId}" style="color:#4f2d99;">View campaign</a></p>
  <p style="color:#6b6b80;font-size:12px;">— Fundable Protocol</p>
</div>`;

  return { subject: `${campaignName}: ${label}`, html };
}

// ── Handler ───────────────────────────────────────────────────────────────────

/** Impact metrics that can be forwarded alongside a milestone event. */
export interface DispatchMilestoneMetrics {
  treeCount?: number;
  verifiedTreeCount?: number;
  co2OffsetKg?: number;
  sponsorCount?: number;
  raisedAmount?: string;
  goalAmount?: string;
  location?: string;
}

interface DispatchBody {
  event?: ProgressEvent;
  campaign?: {
    id?: string;
    name?: string;
    progressPct?: number;
    trees?: number;
  };
  /** Impact metrics forwarded from the contribution service for milestone emails. */
  metrics?: DispatchMilestoneMetrics;
}

/**
 * POST /api/notifications/dispatch
 *
 * Two modes:
 *  - No body (or `{}`): send due progress digests to every sponsor whose
 *    frequency interval has elapsed.
 *  - `{ event: { type: "milestone", milestoneKey, ... }, campaign: {...} }`:
 *    milestone events notify **all** sponsors of that campaign immediately,
 *    regardless of frequency.
 *
 * Returns a per-delivery report. Failures never abort the loop.
 */
export async function POST(request: Request) {
  let body: DispatchBody = {};
  try {
    const text = await request.text();
    if (text.trim()) body = JSON.parse(text) as DispatchBody;
  } catch {
    return Response.json({ error: "invalid JSON body" }, { status: 400 });
  }

  const event = body.event;
  const deliveries: Array<{
    sponsorId: string;
    channel: string;
    ok: boolean;
    kind: "digest" | "milestone";
    error?: string;
  }> = [];

  try {
    if (isMilestoneEvent(event)) {
      const campaignId = String(body.campaign?.id ?? "");
      if (!campaignId) {
        return Response.json({ error: "campaign.id is required for milestone events" }, { status: 400 });
      }
      const prefs = await getPreferencesForCampaign(campaignId);

      // Build impact metrics from the forwarded payload (set by the contribution
      // service for #915 sponsor notifications).
      const rawMetrics = body.metrics;
      const impactMetrics: MilestoneEmailImpactMetrics | undefined =
        rawMetrics &&
        typeof rawMetrics.treeCount === "number" &&
        typeof rawMetrics.co2OffsetKg === "number" &&
        typeof rawMetrics.sponsorCount === "number" &&
        typeof rawMetrics.raisedAmount === "string" &&
        typeof rawMetrics.goalAmount === "string"
          ? {
              treeCount: rawMetrics.treeCount,
              verifiedTreeCount: rawMetrics.verifiedTreeCount,
              co2OffsetKg: rawMetrics.co2OffsetKg,
              sponsorCount: rawMetrics.sponsorCount,
              raisedAmount: rawMetrics.raisedAmount,
              goalAmount: rawMetrics.goalAmount,
              location: rawMetrics.location,
            }
          : undefined;

      const content = renderMilestoneEmail(
        campaignId,
        String(body.campaign?.name ?? "A campaign you sponsor"),
        event.milestoneKey,
        impactMetrics,
      );

      for (const p of prefs) {
        try {
          if (p.channel === "email") {
            await emailService.sendEmail({ to: p.email!, subject: content.subject, html: content.html });
          } else {
            // Push channel: logged for now; a push provider plugs in here.
            console.log(`[push] ${p.pushEndpoint} ← ${content.subject}`);
          }
          deliveries.push({ sponsorId: p.sponsorId, channel: p.channel, ok: true, kind: "milestone" });
        } catch (err) {
          deliveries.push({
            sponsorId: p.sponsorId,
            channel: p.channel,
            ok: false,
            kind: "milestone",
            error: err instanceof Error ? err.message : String(err),
          });
        }
      }
      return Response.json({ mode: "milestone", sent: deliveries.filter((d) => d.ok).length, deliveries });
    }

    // Digest mode: only sponsors whose interval has elapsed.
    const due = await getDueDigests();
    const campaign = body.campaign ?? {};

    for (const p of due) {
      try {
        const content = renderDigestEmail(
          p.campaignId,
          String(campaign.name ?? "A campaign you sponsor"),
          Number(campaign.progressPct ?? 0),
          Number(campaign.trees ?? 0),
        );
        if (p.channel === "email") {
          await emailService.sendEmail({ to: p.email!, subject: content.subject, html: content.html });
        } else {
          console.log(`[push] ${p.pushEndpoint} ← ${content.subject}`);
        }
        await markNotified(p.campaignId, p.sponsorId);
        deliveries.push({ sponsorId: p.sponsorId, channel: p.channel, ok: true, kind: "digest" });
      } catch (err) {
        deliveries.push({
          sponsorId: p.sponsorId,
          channel: p.channel,
          ok: false,
          kind: "digest",
          error: err instanceof Error ? err.message : String(err),
        });
      }
    }

    return Response.json({ mode: "digest", sent: deliveries.filter((d) => d.ok).length, deliveries });
  } catch {
    return Response.json({ error: "dispatch failed" }, { status: 500 });
  }
}
